= Rapid development with Javascript
:page-pagination:

== General

Javascript renderer can retrieve the script from the classpath as well as from external server.

We can use this feature together with `webpack` and `webpack-dev-server` to prepare a setup for rapid development of templating and view logic.

== Script development

First let's define the Javascript renderer bean tailored for development.

.SpringConfiguration.java
[source,java]
----
@Bean
JavascriptRenderer provideJavascriptRenderer(WebClient webClient, ObjectMapper mapper) {
  return JavascriptRendererConfigurator.instance()
      .objectMapper(mapper)
      .externalScript(builder -> builder
          .webClient(webClient)
          .uri("http://localhost:3000/bundle.js"))
      .buildDevelopment();
}
----

.application.properties alternative
[source,properties]
----
markuply.javascript.bundle=http://localhost:3000/bundle.js
----

.application.yml alternative
[source,yaml]
----
markuply:
  javascript:
    bundle: "http://localhost:3000/bundle.js"
----

The second step is to setup webpack build and start the dev server.

The server starting command should look like this: `webpack-dev-server --open --no-inline`. 
`no-inline` parameter is important as otherwise `webpack` will inject not server side friendly code into the final JS bundle.

Markuply will now reload the script each time webpack produces a new bundle.

== Template development

While `webpack-dev-server` is mainly about fast script development it can also be used to provide and modify the original HTML content processed by Markuply.

As with any other customization you just have to define your own `HttpPageRepository` bean.

.SpringConfiguration.java
[source,java]
----
@Bean
HttpPageRepository providePageRepository(HttpPageRepositorySpringConfigurator configurator) {
  return configurator
      .urlPrefix("http://localhost:3000/pages")
      .build();
}
----

.application.properties variant
[source,properties]
----
markuply.http.repository.baseUrl=http://localhost:3000/pages
----

.application.yml variant
[source,yaml]
----
markuply:
  http:
    repository:
      baseUrl: "http://localhost:3000/pages"
----

The definition above assumes HTML files are exposed by `webpack-dev-server` under the `/pages` path. 
