name: Test

on: 
  [push, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the selected branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify build
      run: ./gradlew build javadoc
